# Generated by Django 2.2.4 on 2019-11-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhymesapp', '0003_auto_20191029_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='streetaddress',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.RemoveField(
            model_name='account',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='account',
            name='street_address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
