# Generated by Django 2.2.4 on 2019-11-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhymesapp', '0005_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
    ]
